Fix string recognition of ro channel map because of representation sa…
QudevETH/PycQED_py3 pull request #20
Opened 2019-10-10 15:31 UTC by nathlacroix

Fixes #17
The readout channel map was wrongly acquired due to the string representation of the string. 

The pycqed code has been revised and no other instances have been found with similar issues, as all other cases look for parameter values (i.e. float) where repr(value) == str(value). If accessing a string value from the HDF file, one should apply eval on it.

2019-10-17 11:46 UTC, antsr commented
But `acq_weights_type` is not the only string parameter in the hdf5 files. We have all the pulse types and channel names, for example.

2019-10-17 12:40 UTC, stephlazar commented
@antsr that is true, but I think what Nathan did is to fix all instances in PycQED where string parameters are extracted from HDF5 file, by adding eval. In the future, we should always eval whenever we extract.

2019-10-17 21:50 UTC, nathlacroix commented
All the instances I have found (approx. 300) are either outdated functions in the analysis toolbox or they look for parameters which are numbers, hence eval(value) == value . But maybe I overlooked some of them. We can check that together @stephlazar

2019-10-18 10:11 UTC, stephlazar commented
@antsr @nathlacroix I made more changes. Please review.

2019-10-18 13:32 UTC, antsr requested changes
thanks for the changes, @stephlazar 
the `FluxDecoupler` class should not be deleted, it should still work and might be useful.
Also, I think that when we do an `eval`, we shouldn't have to do any further casting, e.g. `str(eval(...` and `float(eval(...` and `int(eval(...` should be replaced with just `eval(...`

2019-10-18 13:32 UTC, antsr commented on pycqed/analysis/analysis_toolbox.py
> +        qbchs = [str(eval(instr_settings[qbn].attrs['acq_I_channel']))]
`str` should not be needed anymore

2019-10-18 13:32 UTC, antsr commented on pycqed/analysis/analysis_toolbox.py
> +            param_val = float(eval(instr_settings[instr_name].attrs[
`float` should not be needed anymore with eval

2019-10-18 13:32 UTC, antsr commented on pycqed/analysis/measurement_analysis.py
> +        logger.warning('Could not import pygsti')
Not a critical issue, but just to raise awareness, that the logger object is usually (in other modules of PycQED) called `log`. I know it was a problem already before.

2019-10-18 13:32 UTC, antsr commented on pycqed/instrument_drivers/meta_instrument/FluxDecoupler.py
> -import numpy as np
This class should still be working. I wrote it at some point to store and use the flux decoupling matrix. I would not delete it.

2019-10-18 13:43 UTC, nathlacroix reviewed
@stephlazar thanks for the changes and the clean up !
I will address the comments of @antsr asap (this weekend or next week)

2019-10-18 13:55 UTC, stephlazar commented
@nathlacroix I already did :)

2019-10-18 13:55 UTC, antsr approved these changes

2019-10-18 13:56 UTC, stephlazar submitted a review, later dismissed
Now it looks ok

2019-10-21 07:49 UTC, stephlazar commented
I have now tested a few standard analyses that we run and fixed a small bug.
Analyses tested: Rabi with SSB weights, Rabi with classifier and active reset, Ramsey (SSB), QScale (SSB), T1 (SSB), Flux pulse scope, Chevron. 

The pull request can be mearged from my point of view.

2019-10-21 12:02 UTC, merged