Pulses with mirror pattern
QudevETH/PycQED_py3 pull request #228
Opened 2021-03-31 10:38 UTC by chellings

This PR adds the possibility to specify a mirror_pattern in a pulse, which defines whether and how to mirror the amplitude of the pulse when the pulse is used repeatedly. This can be used to implement toggling unipolar CZ gates.

Inviting @nathlacroix to review.
FYI @stephlazar @antsr

2021-07-09 09:01 UTC, nathlacroix requested changes
Very useful feature, basic functionality successfully tested on real setup. 

requested change:
- please add documentation (at the most convenient/logical place for user) about the different accepted patterns and what they mean

possible improvements in the future (beyond this pull request):
- I believe the mirror pattern isn't always added as a pulse parameter in the operations dict, meaning that it cannot be easily accessed. Is that correct? It would make sense in the future, to have it for any type of pulse and have it easily accessible.

2021-07-09 09:01 UTC, nathlacroix commented on pycqed/measurement/waveform_control/segment.py
> +        """
Please detail here and/or where the user would typically add the mirror pattern (in the pulse object, I guess) what patterns are accepted and what they mean. I couldn't find such documentation

2021-07-20 18:46 UTC, chellings commented on pycqed/measurement/waveform_control/segment.py
> +        """
done

2021-07-23 14:28 UTC, merged

2021-07-23 14:29 UTC, nathlacroix reviewed
thanks 👍